// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again:
// With a Flutter package, run `flutter pub run build_runner build`.
// With a Dart package, run `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'db/clip/clip.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
      id: const obx_int.IdUid(1, 4409021528291857207),
      name: 'Clip',
      lastPropertyId: const obx_int.IdUid(5, 1435996780013244804),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 8027769434755693552),
            name: 'localId',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 7863524828696527756),
            name: 'id',
            type: 9,
            flags: 2080,
            indexId: const obx_int.IdUid(1, 4517137118427836160)),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 210672860375023786),
            name: 'created',
            type: 10,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 6051413520983539760),
            name: 'lastSynced',
            type: 10,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(5, 1435996780013244804),
            name: 'text',
            type: 9,
            flags: 0)
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[])
];

/// Shortcut for [Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore(
    {String? directory,
    int? maxDBSizeInKB,
    int? maxDataSizeInKB,
    int? fileMode,
    int? maxReaders,
    bool queriesCaseSensitiveDefault = true,
    String? macosApplicationGroup}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(getObjectBoxModel(),
      directory: directory ?? (await defaultStoreDirectory()).path,
      maxDBSizeInKB: maxDBSizeInKB,
      maxDataSizeInKB: maxDataSizeInKB,
      fileMode: fileMode,
      maxReaders: maxReaders,
      queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
      macosApplicationGroup: macosApplicationGroup);
}

/// Returns the ObjectBox model definition for this project for use with
/// [Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
      entities: _entities,
      lastEntityId: const obx_int.IdUid(1, 4409021528291857207),
      lastIndexId: const obx_int.IdUid(1, 4517137118427836160),
      lastRelationId: const obx_int.IdUid(0, 0),
      lastSequenceId: const obx_int.IdUid(0, 0),
      retiredEntityUids: const [],
      retiredIndexUids: const [],
      retiredPropertyUids: const [],
      retiredRelationUids: const [],
      modelVersion: 5,
      modelVersionParserMinimum: 5,
      version: 1);

  final bindings = <Type, obx_int.EntityDefinition>{
    Clip: obx_int.EntityDefinition<Clip>(
        model: _entities[0],
        toOneRelations: (Clip object) => [],
        toManyRelations: (Clip object) => {},
        getId: (Clip object) => object.localId,
        setId: (Clip object, int id) {
          object.localId = id;
        },
        objectToFB: (Clip object, fb.Builder fbb) {
          final idOffset =
              object.id == null ? null : fbb.writeString(object.id!);
          final textOffset =
              object.text == null ? null : fbb.writeString(object.text!);
          fbb.startTable(6);
          fbb.addInt64(0, object.localId);
          fbb.addOffset(1, idOffset);
          fbb.addInt64(2, object.created.millisecondsSinceEpoch);
          fbb.addInt64(3, object.lastSynced?.millisecondsSinceEpoch);
          fbb.addOffset(4, textOffset);
          fbb.finish(fbb.endTable());
          return object.localId;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final lastSyncedValue =
              const fb.Int64Reader().vTableGetNullable(buffer, rootOffset, 10);
          final localIdParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);
          final idParam = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 6);
          final createdParam = DateTime.fromMillisecondsSinceEpoch(
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 8, 0));
          final lastSyncedParam = lastSyncedValue == null
              ? null
              : DateTime.fromMillisecondsSinceEpoch(lastSyncedValue);
          final textParam = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 12);
          final object = Clip(
              localId: localIdParam,
              id: idParam,
              created: createdParam,
              lastSynced: lastSyncedParam,
              text: textParam);

          return object;
        })
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [Clip] entity fields to define ObjectBox queries.
class Clip_ {
  /// see [Clip.localId]
  static final localId =
      obx.QueryIntegerProperty<Clip>(_entities[0].properties[0]);

  /// see [Clip.id]
  static final id = obx.QueryStringProperty<Clip>(_entities[0].properties[1]);

  /// see [Clip.created]
  static final created =
      obx.QueryDateProperty<Clip>(_entities[0].properties[2]);

  /// see [Clip.lastSynced]
  static final lastSynced =
      obx.QueryDateProperty<Clip>(_entities[0].properties[3]);

  /// see [Clip.text]
  static final text = obx.QueryStringProperty<Clip>(_entities[0].properties[4]);
}
